### ISSUE TITLE
Cambiar el nombre de la sección codenautas por qa-control

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#11]
Así es más genérico y se puede usar aunque no sea del grupo codenautas.

También hay que pensar que las reglas tienen que ser apagables o modificables desde un .yaml (eso lo vamos a hacer después, más adelante, cuando lo necesitemos, total ya sabemos que podemos).

**Comment by diegoefe** [comment]
Esto creo que ya está
