### ISSUE TITLE
Agregar regla codenautas_code_customs

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#12]
Agregar en qaDefinitions una sección costums (costumbres). 

Esas costumbres tienen la forma detect/match. Si se encuentra dentro del código .js una línea que contenga "detect" esa línea debe contener "match". En caso de que se detecte y no machee el warning debe ser file_1_not_match_custom_2 (en castellano: "$1 no respeta la costumbre $2")

```js
costums:{
   funtion_eid:{
      detect:'function eid',
      match:'function eid(id){ return document.getElementById(id); }'
   },
   var_winos:{
      detect:'var winos',
      match:"var winOS = Path.sep==='\\';"
   }
}
```
podría generar:
```j
[{warning: file_1_not_match_custom_2, params:['server.js', 'function eid']}]
```

La coincidencia con detect es incase sensitive y la coincidencia con match es case sensitive.

**Comment by diegoefe** [comment]
Si bien la palabra "costums" existe en el traductor de google (aunque curiosamente no existe el singular...), opino que más estándard y claro sería algo como "practices" o "best practices".
costum/s no existe en el Longman

**Comment by emilioplatzer** [comment]
Prefiero costum (costumbre). Me gusta la acepción de http://www.ldoceonline.com/dictionary/custom_1

Creo que refleja más una costumbre, porque prefijos del .js puede haber muchos, todos ser buenas prácticas y algunos mejores que otro.

**Comment by emilioplatzer** [comment]
Prefiero costum (costumbre). Me gusta la acepción de http://www.ldoceonline.com/dictionary/custom_1

Creo que refleja más una costumbre, porque prefijos del .js puede haber muchos, todos ser buenas prácticas y algunos mejores que otro.

**Comment by diegoefe** [comment]
Ok

**Comment by emilioplatzer** [comment]
cambiar costum por custom.
