### ISSUE TITLE
Agregar la regla first_lines para controlar las primeras líneas según "run-in"

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#14]
Según el valor de "run-in", las primeras líneas del archivo .js especificado en packageJson.main debe ser igual al que está en: *qac.projectDefinition['0.0.1'].sections['run-in'].values[value].firstLines*

Si no machea debe informar un warning. 

Para que machee los fines de línea pueden ser cualquiera (tanto en el fuente como en la especificación de firstLines) y la palabra nombreDelModulo debe coincidir con packageJson.name pero camelizado.

**Comment by diegoefe** [comment]
Esta regla la ejecuto sólo si existe packageJson.main o creo una regla que garantice que esta sección sea obligatoria para ejecutarla siempre?

**Comment by emilioplatzer** [comment]
Si no está se considera que main es ./index.js

**Comment by diegoefe** [comment]
ok
