### ISSUE TITLE
custom.detect puede ser una regexp, si es un string utilizar la funcion softRegExp

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#15]
1. Hacer que custom dependa de la versión
  2. permitir regexp como parámetro
  3. crear custom.softRegExp=function(string){ return regexp; } modificando regexp para que:
      1. case insensitive
      2. los espacios son siempre \s+ 
      3. el igual delante y después de una letra tiene como separador \s*

Caso de prueba
  * detect: var path=require('hola');
  * match: var      Path = require('hola');

Caso de prueba que no machea con el mismo detect
  * match varPath=require('hola');

**Comment by diegoefe** [comment]
Pensamiento: tanto detect como match podrían ser regexes... cómo lo ves?

**Comment by emilioplatzer** [comment]
Sí, ambos pueden ser tanto un string como un regexp. 

Es más una mejora podría ser que si ambos son regexp se puedan poner paréntesis de captura de un lado y place holders del otro. Eso puede quedar para después, en un nuevo issue, cuando lo necesitemos lo agrego. Lo pongo acá para ir teniendo idea de que eso puede necesitarse.

**Comment by diegoefe** [comment]
ok, por ahora entonces ambos pueden ser regex y los paso por softRegExp

**Comment by emilioplatzer** [comment]
No, detect no tiene que pasar por softRegExp

**Comment by diegoefe** [comment]
Ah, creo que entiendo

**Comment by emilioplatzer** [comment]
Cerrado en 05910fb3835b0fb2ff30c7d03c12f86634a84438
