### ISSUE TITLE
hacer el runner para poder ejecutarlo de la línea de comandos

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#18]
Los parámetros de la línea de comando deben ser los necesarios para:
  1. llamar a controlProject
  2. decir si se quiere verbose o no verbose
  3. seleccionar el idioma de los mensajes
 
Lo que te muestra es un renglón por cada warning y mergeado el $1, $2 con cada parámetro

**Comment by emilioplatzer** [comment]
Y listar los idiomas disponibles

**Comment by diegoefe** [comment]
Cuál es el sentido de la opción --verbose? (para el caso agregué --silent, para que --versbose sea default, aunque aún no hace nada)

**Comment by emilioplatzer** [comment]
Agregué un issue en [multilang #17](https://github.com/codenautas/multilang/issues/17), 

--verbose y --silent deben ser coherentes con esa explicación.

**Comment by diegoefe** [comment]
No entiendo el --silent en una utilidad que que sólo muestra su status por pantalla (excepto por lo de cucardas.log, pero nunca se lo genera sin warnings visibles)

**Comment by emilioplatzer** [comment]
--verbose = con algunos otros mensajes que no son estrictamente warnings (por ejemplo Done!)

--silent = sin mensajes (solo genera log o los archivos que en el futuro digamos que tiene que generar). 

Lo de silent puede quedar para más adelante. Lo de verbose hay que ponerlo en cuanto quieras agregar un console.log que muestre otra cosas que no sea un warning.

**Comment by diegoefe** [comment]
ok. Para agregar --verbose debería agregar el parámetro parameters (supongo que opcional, algo no muy recomendable en JavaScript) a loadProject()/controlInfo()/controlProject().
Otra opción es setearlo en qaControl como una propiedad (no sé cuan recomendable)
Qué opinás? Qué alternativa sigo?
O preferís que saquemos una versión sin --verbose caundo termine de mejorar el coverage?

**Comment by emilioplatzer** [comment]
La lógica creo que debería ser esta: ninguna función debe emitir por la salida
Ponélo como una propiedad global de qaControl.

**Comment by diegoefe** [comment]
ok

**Comment by emilioplatzer** [comment]
La lógica creo que debería ser esta: ninguna función debe emitir por la salida estándar ni por la salida de error absolutamente nada (salvo que esté en la especificación), porque en general los efectos colaterales son indeseados. 

A veces los programadores prefieren dar "alguna señal" mientras programan (emitiendo algunos console.los) para eso, creo, lo mejor es tener una propiedad global de aqControl (verbose) que por defecto esté en false.
