### ISSUE TITLE
controlar la presencia de codenautas en package-json

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#2]
* Fixture: without-codenautas
  * Mensaje devuelto: qaControl.msgs.no_codenautas_section
  * Caso: no figura en ningún lugar la palabra codenautas (ninguno ninguno)

* Fixture: lack-codenautas
  * Mensaje devuelto: qaControl.msgs.no_codenautas_section_in_codenautas_project
  * Español: 'falta la sección codenautas en package.json y aparenta ser un proyecto codenautas'
  * Caso: no hay sección codenautas pero sí figura en algún lugar la palabra codenautas (puede ser cualquier lugar, como parte de una clave o como parte de un valor)

**Comment by diegoefe** [comment]
Listo

**Comment by diegoefe** [comment]
Qué hacemos con este? Tiene sentido?

**Comment by emilioplatzer** [comment]
Sí, tiene sentido. Si figura "codenautas" en algún lugar del texto del packageJson tiene que haber una sección qa-control

**Comment by diegoefe** [comment]
Ah! tenés razón

**Comment by diegoefe** [comment]
El tema es que salta antes (o después) la consistencia de no qa-control section in package.json.
Creo que ambas son obligatorias

**Comment by emilioplatzer** [comment]
es que esa consistencia tiene que devolver dos mensajes distintos de acuerdo a si encuentra "codenautas" o no dentro de package.json text, en uno avisa que no está, en el segundo que no está y debería estar. Es la misma regla con dos warnings distintos.
