### ISSUE TITLE
Agregar un test de integridad que busque todos los ID de warnings

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#24]
El test debe abrir el archivo qa-control.js como un archivo de texto. Buscar todas las ocurrencias de warning: string (ya sea con o sin comillas dobles o simples) y luego verificar que figure en todos los idiomas (salvo inglés que se genera automático). 

Por ejemplo si dentro del código figura:
`{warning:'missing_mandatory_cucarda_1', `

hay que reivsar que esté (porque si no no lo muestra bien en qa-control-run) y siempre nos podemos olvidar de agregarlo.

**Comment by diegoefe** [comment]
Fijate si el test de integridad que agregué te satisface y cerrá el issue si es así.
La ventaja que tiene es que te dice el número de línea de la falla.
La desventaja es que no captura cosas como:
  warning:
      'esto_es_un_warning'
Si no te parece suficiente, avisame que lo extiendo para que soporte más casos

**Comment by diegoefe** [comment]
Con este método detecté que el incorrecto uso de 'missing_mandatory_cucarda_1' cuando iba 'lack_of_mandatory_cucarda_1'

**Comment by emilioplatzer** [comment]
Agregá que no permita `warning:` sin nada después, así obligamos a que esté
en la misma línea

**Comment by diegoefe** [comment]
ok
