### ISSUE TITLE
controlar la version

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#3]
* Fixture: lack-version
  * Mensaje devuelto: qaControl.msgs.no_version_in_section_codenautas
  * Español: 'falta la entrada para "package-version" en la sección codenautas del package.json'
  * Caso: hay sección codenautas (después de éste todos los nuevo fixtures tienen codenautas y versión 0.0.1 salvo que se indique lo contrario), pero falta la entrada package-version

**Comment by diegoefe** [comment]
Listo
