### ISSUE TITLE
el control del contenido de .gitignore no debe abortar

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#30]
Con 
Por ejemplo con https://github.com/codenautas/fast-devel-server/commit/8d34ad035c8b98bd2b737b3916180caf63a7e14c si corro qa-control

```sh
c:\Hecho\npm\fast-devel-server>qa-control .
lack of mandatory line local-* in file .gitignore
lack of mandatory line *-local.* in file .gitignore
```
agrego esas dos líneas en `.gitignore` y vuelvo a correr qa-control

```sh
c:\Hecho\npm\fast-devel-server>qa-control .
lack of cucarda marker in readme
lack of mandatory cucarda npm-version
wrong format in cucarda coverage
first lines does not match in file index.js
jshint warnings in file index.js
```

**Comment by diegoefe** [comment]
Podemos decir que ninguna de las "mandatoryLines" deberían abortar? (por ahora existe sólo para .gitignore, pero podrían agregarse más para otros)
O este requerimiento es válido sólo para .gitignore?

**Comment by emilioplatzer** [comment]
Sí, la regla debería ser para esto y para todo. Salvo que especifiquemos lo
contrario ningún warning debe abortar.

2015-08-24 12:39 GMT-03:00 Diego Florio <notifications@github.com>:
