### ISSUE TITLE
No coinciden los warnings de jshint a través de qa-control

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#32]
Lo probé instalando jshint y qa-control en el mismo momento. Quizás tengamos que hacer que informe cuáles son los warnings (si es que se puede con la librería que usamos, aunque sea en la versión --verbose)

```sh
c:\Hecho\npm\fast-devel-server>qa-control .
jshint warnings in file server/server.js

c:\Hecho\npm\fast-devel-server>jshint server/server.js

c:\Hecho\npm\fast-devel-server>
```

**Comment by diegoefe** [comment]
Con la última versión de qa-control y la última de jshint no me da diferencias

**Comment by diegoefe** [comment]
Esto era por el BOM, creo que ya está. Reabrir en caso contrario
