### ISSUE TITLE
En test de integridad verificar que ningún archivo js tenga BOM

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#33]
Los que están en bin y sus carpetas.

**Comment by diegoefe** [comment]
Qué te parece incluir todo lo que haya en bin, inclusive los .txt que pueden tener BOM?
Lo digo porque así se puede sacar el stripBom() del escaneo de entrada (firstLines)

**Comment by emilioplatzer** [comment]
ok. También se pueden ir agregando otros archivos de texto a medida que necesitemos.
