### ISSUE TITLE
Si no existe el archivo que está en "main" hay que dar un warning lindo y no un ENOENT

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#37]

**Comment by diegoefe** [comment]
Este problema existe desde el principio del proyecto. Qué hacer cuando se detecta un error cuando se están levantando la información, etapa en la que no se devuelven warnings.
Si mostrar de manera no elegante es inaceptable, se podría crear una regla inicial (llamada p.e. "file_content") con shouldAbort=true pero, conviene/corresponde abortar si un archivo no existe?

**Comment by diegoefe** [comment]
El problema es que no sabemos cuantas reglas van a utilizar el contenido de un archivo como para capturar el error en esos lugares (lidiando con un content=='undefined')

**Comment by emilioplatzer** [comment]
en el momento en que dentro de qa-control accedemos a .content tenemos que controlar que el archivo exista y mostrar un warning de que no existe si no existe.

**Comment by diegoefe** [comment]
Se accede desde varias reglas...
