### ISSUE TITLE
La versión está despreciada

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#4]
* Fixture: deprecated-version
  * Mensaje devuelto: qaControl.deprecated_version
  * Español: 'la version % es demasiado vieja'
  * params esperado: el número de versión encontrada
  * Caso: tiene package-version:'0.0.0'. 

El módulo qa-control tiene una propiedad llamada 
```js
qaControl.deprecateVersionesBefore = '0.0.1';
```

Que iremos cambiando a medida que querramos despreciar versiones.

**Comment by diegoefe** [comment]
Listo

**Comment by diegoefe** [comment]
Cómo manejamos esto?
Imagino que si la versión es vieja usamos los checks de esa versión pero lanzamos el warning. Cómo lo ves?
Para testearlo podría modificar projectDefinition y restaurarlo, pero eso no te gusta, alguna idea?

**Comment by emilioplatzer** [comment]
Solo es dar un warning si la versión está despreciada. Para problarlo en el change del caso de prueba hay que poner info.packageJson.qa-control.package-version='0.0.0' y listo. 

Lo de ver de qué versión se usan las reglas lo probamos después.

**Comment by diegoefe** [comment]
ok, pero tengo que abortar (o restaurar) porque sino fallan las reglas
siguientes

2015-07-28 10:40 GMT-03:00 Emilio <notifications@github.com>:

**Comment by emilioplatzer** [comment]
puede ser una regla de abort como cuando no hay packageJson

**Comment by diegoefe** [comment]
Ok, pero el problema es que qac es global y habría que restaurarlo para siguientes tests. O crear un qac para cada test...

**Comment by emilioplatzer** [comment]
No, porque el change de la regla solo cambia el info y el info ya está clonado. No hace falta restaurar nada.

**Comment by diegoefe** [comment]
Verdad otra vez, perdón
