### ISSUE TITLE
Controlar "use strict";

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#43]
Cualquier renglón cuyo primer carácter no blanco sea una comila doble o simple. Que además la línea anterior no existe o termina con una llave que abre; debe controlar que diga "use strict";

**Comment by emilioplatzer** [comment]
Solo para la ultima versión de reglas 0.1.4

**Comment by diegoefe** [comment]
Hay que controlar sólo que esté bien escrito (para estos casos) y no que exista, no?

**Comment by emilioplatzer** [comment]
que no exista no hay que controlar porque en un archivo `"use strict";` puede estar más de una vez.

**Comment by diegoefe** [comment]
Además de hacerlo en la ubicación correcta, lo que hay que controlar es que no esté mal escrito (el spelling), correcto?

**Comment by emilioplatzer** [comment]
Sí. O que no diga otra cosa
