### ISSUE TITLE
--init debe deducir el repositorio en base al nombre

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#44]
actualmente sugiere /npm en vez de /nombre-del-repo

**Comment by diegoefe** [comment]
Corriéndolo cómo?
Si te parás en un directorio vacío, p.e.: c:\minuevoproyecto y corrés qa-control -i sugiere 'minuevoproyecto'

**Comment by emilioplatzer** [comment]
si ponés qa-control --init y cuando te pregunta el nombre del proyecto le ponés `este-proyecto` el repositorio debe terminar en `/este-proyecto` ahora termina en `/npm` o sea no toma el nombre del proyecto que contestaste en la primera pregunta.

**Comment by diegoefe** [comment]
Qué versión de node estás usando?
El os es windows?
Por ahora la carpeta del nuevo proyecto debe existir,  
Cuál es el comando exacto qué estás usando y dónde estás parado?

**Comment by emilioplatzer** [comment]
Estás confundiendo nombre de proyecto con nombre de repositorio. Si te pregunta el nombre del proyecto es porque lo podés cambiar si lo cambiás debe sugerirlo en el nombre del repositorio. Ahí va una corrida, la última sugerencia está mal debe sugerir `este-proyecto`.

```sh
C:\hecho\npm\cualquiera>qa-control --init
Project name: (cualquiera) este-proyecto
Project description: la descripcion
Project version: (0.0.1)
Author: (Codenautas <codenautas@googlegroups.com>)
Repository: (https://github.com/codenautas/cualquiera)
```

En Repository debe decir este-proyecto y no cualqueira (que es el nombre de la carpeta)

**Comment by diegoefe** [comment]
Creo que entendí
