### ISSUE TITLE
--init debe basar el .gitignore en la versión actual de gitingnore

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#49]
Generar un .gitignore ahora de un repositorio nuevo y usar esa como base.

**Comment by diegoefe** [comment]
Cuál es la versión actual? No deberíamos mantener al día \bin\init-template\dot-gitignore y listo?

**Comment by emilioplatzer** [comment]
La versión actual es la que genera automáticamente github cuando ponés
crear un repositorio nuevo y ponés que es un proyecto Node.

Seteálo para la primera vez con lo que genere al día de hoy con el agregado
de los local-... para que sea compatible con qa-control.

Después yo lo mantengo
