### ISSUE TITLE
Faltan los parámetros obligatorios

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#5]
* Fixture: incomplete-codenautas-section
  * Test:
    * Mensaje devuelto: qaControl.msgs.lack_mandatory_parameter
    * Español: 'falta el parámetro obligatorio %'
    * params esperado: el nombre del parámetro que falte
    * caso: la sección vacía (en realidad solo la versión 0.0.1), espera que detecte la falta de run-in

* Fixture: invalid-codenautas-section
  * Test:
    * Mensaje devuelto: qaControl.msgs.invalid_value_1_in_parameter_2
    * Español: 'el parámetro $2 tiene un valor inválido $1'
    * params esperado: el nombre del parámetro que falte y su valor
    * caso 'run-in': 'deep space'

Acá me doy cuenta que los mensajes no tienen que tener un placeholder '%' (no posicional) sino uno posicional (porque en cada idioma podría estructurarse distinto el orden de la oración). Cambiar los % de antes por $1, $2, etc.

debería existir algo así:

```js
qaControl.packageJsonDef = {
  '0.0.1': {
    sections: {
      run-in: {
        mandatory: true,
        values: {
          server:{},
          both: {},
          client: {}
        }
      },
      type: {
        mandatory:true
      }
    }
  }
}
```

**Comment by diegoefe** [comment]
No entiendo el mandatory:true de type

**Comment by diegoefe** [comment]
Entendido

**Comment by diegoefe** [comment]
No entiendo esto: qaControl.msgs.invalid_value_1_in_parameter_2.
Tampoco me queda claro cómo se usa (para checkear) sections[section].value

**Comment by emilioplatzer** [comment]
sections[section].values tiene los valores permitidos, si no está ahí como clave no está permitido como valor

**Comment by diegoefe** [comment]
Y porqué es un objeto?

**Comment by emilioplatzer** [comment]
porque un objeto es un hash y se puede acceder en forma eficiente para consultar en O(log n) así
```js
sections[section].values[valueObtained]
```

si fuera un array habría que consultarlo con IndexOf que es O(n). 

Además así queda reservado para futuros usos la descripción que pueda tener el valor. 

Hay que tratar de evitar siempre verificar cosas con conjunto.indexOf(valor) si se puede consultar conjunto[valor]. En todos los casos, salvo cuando los datos ya vengan en formato arreglo (entonces ahí hay que evaluar si la conversión a hash no termina siendo más costosa en función de cuántas consultas hay que hacerle.
