### ISSUE TITLE
Ningún parámetro de --init debe ser obligatorio. No cortar el input

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#50]
Ningún parámetro debe ser obligatorio (si no se ingresa debe quedar en blanco) por ejemplo contributors. 

Si hay un error en el formtado de algo de lo ingresado (por ejemplo contributors) hay que volver a preguntar y no cortar.

**Comment by diegoefe** [comment]
"description" puede quedar en blanco?

**Comment by emilioplatzer** [comment]
Ponéle que el default sea "xxx module" y listo

**Comment by diegoefe** [comment]
ok

**Comment by diegoefe** [comment]
Entiendo esto:
- Si se ingresa algo incorrecto, repreguntar
- Si no se ingresa nada, queda en blanco o con el default (si existe)?
  - Si queda en blanco, la entrada va o no en el package.json resultante? (p.e. aparece el key 'contributors' o no?)

**Comment by emilioplatzer** [comment]
Si no tiene default que no esté.

**Comment by diegoefe** [comment]
ok
