### ISSUE TITLE
mejorar el control de "use strict"; #43 para que acepte strings como keys en object definitions

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#51]
Según como lo había definido no acepta: 

```js
{
   'algo asi': 'esta bien'
}
```

Hay que agregar a la regla que para dar warning no debe haber un signo de dos puntos en la línea. Así ese no da warning. 

Se puede probar con tedede que da errores por eso

**Comment by emilioplatzer** [comment]
Relacionado a #43

**Comment by emilioplatzer** [comment]
Mejorar los casos de prueba de esto. Tuve que hacer una modificación de emergencia (en c0fd646cbb13cf7ef9e3d1a55aea6a2158c3a3cd) para que no de warnings. 

La idea es que acepte cualquier objeto indexado por strings (independientemente de si está o no de si la línea actual está precedida por otra clave con strings o no). Por ejemplo tiene que acetar:

```js
f({
    algo: {
    },
    "esto así:"asdfasd",
    "esto otro": 1
    aquello: null,
    "mas uno": [ 
        "etc", 
        "etc",
        "etc",
    ]
}
```

**Comment by emilioplatzer** [comment]
Obviamente también tiene que rechazar:

```js
function pepe(
   " use pirip";
)
```

y las variantes antes mencionadas de strings sueltos en la primera línea de una definición de función o al principio de un archivo.

**Comment by diegoefe** [comment]
Este último no es un error de sintaxis?

**Comment by emilioplatzer** [comment]
sí, quise decir:
```js
function pepe(){
   " use pirip";
}
```

**Comment by diegoefe** [comment]
Podríamos decir que debe fallar requiriendo "use strict"; si:

- No hay linea previa
- La línea previa termina en '{' y no tiene un ':'

Falta algo?

**Comment by emilioplatzer** [comment]
Creo que no. Donde dice "no tiene un ':' " se refiere a la actual, no a la previa. ¿Te parece?

**Comment by diegoefe** [comment]
No, tenés razón, ya estoy haciendo algo más elaborado
