### ISSUE TITLE
Crear la versión (package-version) 0.2.0

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#52]
En la versión 0.2.0:

- ya no hay que poner en las first-lines `globalstrict:true`
- cuando el "run-in" == server hay que aceptar ecmaScript versión 6 (en los demás casos no). 

Para aceptar ecmaScript 6 hay que poner en el package.json:

```js
  "jshintConfig": {
    "asi": false,
    "forin": true,
    "curly": true,
    "esversion": 6
  },
  "eslintConfig": {
    "env": {
      "node": false
    },
    "rules": {
      "strict": 0,
      "no-console": 1,
      "no-unused-vars": 1
    },
    "parserOptions": {
      "ecmaVersion": 6
    }
  },
```

para probar usar [el proyecto pizarra](https://github.com/emilioplatzer/pizarra.git)

**Comment by diegoefe** [comment]
No te parece que podría ser apropiado subir engines.node también:
"engines": {
    "node": ">= 0.12.0"
  },

**Comment by diegoefe** [comment]
La opción "**esversion**" de jshint existe a partir de la versión 2.9.0.
Al actualizar qa-control, tengo warnings para los fixtures que corren versión 0.1.3 (al menos):
**'Incompatible values for the \'strict\' and \'globalstrict\' linting options...'**
Alguna sugerencia?

**Comment by emilioplatzer** [comment]
A) Tener en cada versión una White List de warnings que no nos joden

B) pasarle más opciones a eslint para apagar ese control

**Comment by diegoefe** [comment]
Es jshint, no eslint.
Si uso la versión vieja, no tengo esversion y falla cuando encuentra la opción
Si uso la nueva, no acepta globalstrict=true y no encontré como apagar un error de opción (no de código)

**Comment by emilioplatzer** [comment]
Usa la nueva y
A) filtrá la salida o
B) agregá como configuración inicial o como opción (de alguna de las
múltiples maneras posibles) que no controle eso

**Comment by diegoefe** [comment]
A) No se puede porque fallan todos los first_lines (excepto los de 0.2.0)
B) No se pueden deshabilitar los code: 'E...' errores, no warnings, en especial E059 (conflicto entre los valores de strict y gobalstrict), o aún no encontré la manera
Todos los tests de stable-project (0.1.3), que son la mayoría, tienen este problema

**Comment by emilioplatzer** [comment]
A se puede siempre. La lista de warnings que recibís la pasás por un filtro
que que ese warning y ya no hay warnings.

**Comment by emilioplatzer** [comment]
Veo que la opción B se puede basar en --config, se pueden recopilar las
opciones, agregar las que sea, guardar eso en un archivo temporal y
pasárselo con --config

Usando el API (http://jshint.com/docs/api/) es más fácil porque el objeto
con las opciones se pasa directamente

2016-03-22 18:56 GMT-03:00 Emilio Platzer <emilioplatzer@gmail.com>:

**Comment by diegoefe** [comment]
Ok, me fijaré, pero vos estás seguro de que los E? pueden anularse con opciones?

**Comment by emilioplatzer** [comment]
No, seguro no estoy. Hay que mirar. Si no lo encontrás en las opciones
avisáme

**Comment by diegoefe** [comment]
Ok, te aviso.
