### ISSUE TITLE
Revisar las validaciones de parámetros de --init

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#53]
Si vas a usar expresiones regulares para controlar los parámetros, las expresiones tienen que estar probadas aparte con sus casos de prueba para los casos más comunes. 

Por ejemplo actualmente para autor no acepta espacios para separar nombre de apellido.

**Comment by diegoefe** [comment]
Sugerís que no utilice regexes para validar o que no valide?

**Comment by emilioplatzer** [comment]
Que haya casos de prueba para las regexes para asegurarse que pasan los
obvios. Las regexpes no son muy expresivas que digamos.

Se me ocurre que quizás haya que buscarle una vuelta a esto de las regexes,
quizás tener una biblioteca de regexes nuestra con nombres unificados (y
sus casos de prueba). Si tuviéramos la biblioteca podríamos tener los casos
de prueba en la biblioteca y luego usarla.
