### ISSUE TITLE
Acotar el filtro de *.log (en .gitignore) al directorio raíz

### ISSUE THREAD

**Issue by diegoefe** [codenautas/qa-control#55]
Para que, por ejemplo en qa-control, no ignore cucardas.log cuando no es esperado en un test.
Si bien el test debería fallar en este caso, lo podemos ver/eliminar desde git (con git clean -f)

**Comment by diegoefe** [comment]
Siempre se pueden agregar/modificar .gitignore's locales para permitir los .log

**Comment by emilioplatzer** [comment]
No entiendo para qué pusiste mi label. Si necesitás mi intervención aclarálo en el comentario anterior o posterior a darme intervención.
