### ISSUE TITLE
A veces no reemplaza los underscores en los warnings

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#58]
Por ejemplo 
```sh 
c:\Hecho\npm\js-to-html>qa-control .
lack of mandatory cucarda qa-control
lack_of_eslintconfig_section_in_package_json
jshint warnings in file js-to-html.js
wrong use strict spelling in file js-to-html.js
Done!
```

para ver el error quitar la sección eslintconfig y cambiar alguna cucarda, el warning de las cucardas se ve bien el de eslintconfig no

**Comment by diegoefe** [comment]
Esto es porque lack_of_eslintconfig_section_in_package_json no está agregada a la lista de warnings en qaControl.msgs

**Comment by diegoefe** [comment]
Independientemente de esto, hay que mejorar el test para hacerlo mantenible

**Comment by emilioplatzer** [comment]
Bien. Ya tenemos el bug. Ahora hay que corregirlo. 

Justamente cuando no se encuentre en qaControl.msgs lo que tiene que hacer es reemplazar las "_" por espacios y tratar los números como ya lo hacemos cuando no está en qaControl.msgs en el idioma buscado y sí en otro.

**Comment by diegoefe** [comment]
Ok, aún así, el warning debe ser agregado siempre a la lista general, correcto?

**Comment by emilioplatzer** [comment]
Lo que tiene que ocurrir es que al ejecutar ocurra que en vez de mostrar
```sh
lack_of_eslintconfig_section_in_package_json
```
muestre el mensaje emprolijado

Respecto a controlar que esté siempre la traducción en castellano no es durante la ejecución que debería controlarse sino al correr los casos de prueba (lo cual no parece trivial)

**Comment by emilioplatzer** [comment]
Esperemos a decidir cómo hacer esto último. Queda así entonces.
