### ISSUE TITLE
Crear la nueva directiva qa-control ecmaVersion

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#59]
si en la sección `qa-control` existe `"ecmaVersion": 6` el número debe usarse para llenar la versión en: 

```js
  "jshintConfig": {
    "asi": false,
    "forin": true,
    "curly": true,
    "esversion": 6
  },
  "eslintConfig":{
    "env": {
      "node": false
    },
    "rules": {
      "strict": 0,
      "no-console": 1,
      "no-unused-vars": 1
    },
    "parserOptions": {
      "ecmaVersion": 6
    }
  },
```

si no figura se asume 5

**Comment by diegoefe** [comment]
Entiendo que la regla sería:
- Si existe en qa-control, debe existir y coincidir con las correspondientes  en jshintConfig/eslintConfig
- Si no existe en qa-control, jshintConfig/eslintConfig pueden tener o no cada uno la suya y coincidir o no entre ellas

Esto es correcto? O cómo es?

**Comment by emilioplatzer** [comment]
* sí, existe en `qa-control` debe existir en ambas y coincidir
  * no, si no existe en `qa-control` no deben existir en ninguno de los dos

**Comment by diegoefe** [comment]
Qué pasa si run-in === 'server' y, por ejemplo, jshint requiere { "esversion": 6 }?

**Comment by emilioplatzer** [comment]
Ya no, cambia por esta. Esta regla reemplaza la anterior, porque es una mejora. 

La idea original es que en el server se pudiera usar es6 y que jshint no proteste. 

La mejora actual es indicar si se va a usar es6 para que jshint no proteste unicamente en ese caso

**Comment by diegoefe** [comment]
Entiendo que esta regla es eclipsada por:

- packagejson_main_file_1_does_not_exists
- first_lines_does_not_match_in_file_1
- **lack_of_eslintconfig_section_in_package_json**
- **incorrect_eslintconfig_option_1_in_package_json**
- **lack_of_jshintconfig_section_in_package_json**
- **incorrect_jshintconfig_option_1_in_package_json**

Correcto?
