### ISSUE TITLE
Controlar que estén los archivos que hacen falta

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#6]
* Fixture: invalid-codenautas-section
  * Mensaje devuelto: qaControl.msgs.lack_mandatory_file_1
  * Español: 'falta el archivo obligatorio $1'
  * params esperado: el nombre del archivo
  * caso falta el README.md (porque hasta ahora ese fixture solo tiene package.json) 

en vez de packageJsonDef habría que llamarlo projectDefinition

```js
var projectDefinition={
  '0.0.1': {
    sections:{
       ...
    },
    files:{
      'README.md':{
        mandatory:true
      }
    }
   ...
```

Son obligatorios los siguientes archivos: README.md, LEEME.md, LICENSE, .travis.yml, .gitignore

**Comment by diegoefe** [comment]
Acá tengo la misma duda que en #5, cómo se entiende "qaControl.msgs.lack_mandatory_file_1"
no es mejor devolver varios 'qaControl.msgs.lack_mandatory_file' con diferentes valores? (por ejemplo)

**Comment by emilioplatzer** [comment]
Probablemente haya más cosas para decir de cada archivo

**Comment by emilioplatzer** [comment]
haciéndolo así el costo de programarlo es el mismo, pero el costo de agregarle cosas después es más barato así.
