### ISSUE TITLE
que sea obligatorio poner "files" en package.json

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#60]
Fue un error mío no ponerlo en muchos proyectos, eso hace que se publiquen por ejemplo archivos de test y otras cosas que no se necesitan cuando se instalan como dependientes.

**Comment by diegoefe** [comment]
Entiendo que debería estar al nivel de la regla "mandatory_files", debe tener shouldAbort:true, correcto?

**Comment by diegoefe** [comment]
Para "invalid_files_section_in_package_json" debería validar algo contra info.files, por ejemplo:

- Que no estén incluidos README, CHANGELOG, LICENCE, etc
- Que no estén incluidos los dot files (p.e. .gitignore) y log files
- Que el main file esté incluido (si tal)

Por otra parte se puede fallar con "invalid_files_section_in_package_json" y/o "lack_of_mandatory_file_1"

**Comment by emilioplatzer** [comment]
1. no hace falta shouldAbort, porque los demás controles no dependen de ese
  2. ok
  3. invalid

**Comment by diegoefe** [comment]
3. No importa cuantos sean los errores, devuelvo un "invalid" sin detalles?

**Comment by emilioplatzer** [comment]
Entendí mal la pregunta 3: debe contestar lack si no está la sección files e invalid si es inválida. 

Respecto de los detalles, mejor si hay detalles (aunque sea en el verbose), pero eso manejalo como sea más rápido.

**Comment by diegoefe** [comment]
ok con 3.
**(pregunta 4)**: qué tipo de scoring uso? mandatories?

**Comment by emilioplatzer** [comment]
mandatories, ok

**Comment by diegoefe** [comment]
ok
