### ISSUE TITLE
Crear una regla que verifique si se está controlando contra la última versión de qa-control

### ISSUE THREAD

**Issue by diegoefe** [codenautas/qa-control#61]
Que se genere un warning "not the last version of qa-control-package-version" o similar, con score {notice: 1} y gravity: notice

**Comment by diegoefe** [comment]
Si es un warning global, va a aparecer en todos checks de versiones viejas (problema similar al de jshint de hace algunos días), lo pongo en la versión 0.2.0 y lo mantenemos en subsiguientes?
Alguna idea mejor?

**Comment by emilioplatzer** [comment]
Que lo genere. No es problema mostrar "notice: el package es una versión vieja" y en qa-control-server si solo tiene notices pone ok con un verde y si no tiene nada (es porque está actualizado) pone ok con el otro verde
