### ISSUE TITLE
agregar una lista de dependencias "no recomendadas"

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#68]
Cuando se use una no recomendada que dé un warning. Por ahora las "no recomendadas" son: lodash, best-promise, y promise-plus (que vamos a ir dejando de usarlas en favor del estándar).

**Comment by diegoefe** [comment]
El check es sólo para dependencies, no? (no incluye devDependencies)

**Comment by emilioplatzer** [comment]
Ambas

**Comment by diegoefe** [comment]
ok
