### ISSUE TITLE
Control de README.md y multilang

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#7]
* Fixture: invalid-codenautas-section
  * Mensaje devuelto: qaControl: no_multilang_in_README
  * Español: 'el archivo README.md no es multilang'
  * caso: tiene un README.md común que no es multilang

* Fixture: readme-with-warnings
  * Test:
    * Mensaje devuelto: qaControl: README_multilang_not_synchronized
    * Español: 'falta la sincronización multilang de README.md con $1'
    * caso: el LEEME.md existe pero no es igual al que generaría README.md

(para este último control se podría agregar la funcionalidad en multilang, algo que pregunte cuáles son los archivos no sincronizados; algo de esto ya hay).

**Comment by emilioplatzer** [comment]
Hacer primero el #17

**Comment by diegoefe** [comment]
No entiendo bién el segundo caso:
   Español: 'falta la sincronización multilang de README.md con $1'
Quién es $1?

**Comment by emilioplatzer** [comment]
Puede ser por ejemplo LEEME.md (recordemos que multilang puede tener varios
idiomas y algunos pueden estar sincronizados y otros no)

2015-08-18 15:30 GMT-03:00 Diego Florio <notifications@github.com>:
