### ISSUE TITLE
Programar la función generateCucardas(packageJson)

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control#9]
Leer en estos fixtures el package.json, llamar a la función generarCucardas y ver que es igual al especificado en cucardas.out o que de warnings especificados en warnings.json

Fixtures: todos los que empiezan con cucardas

**Comment by diegoefe** [comment]
Esto necesita aclaración. No entiendo

**Comment by diegoefe** [comment]
Se entiende que hago una de dos cosas:
 1. **primero verifico si existe warnings.json**, comparo su contenido con la salida de los chequeos, o, de lo contrario
 2. ***si no existe, chequeo cucardas.out*** contra la salida de generarCucardas()

Correcto?
